### ISSUE TITLE
SendText to iTerm2 Build 2.9.20151023-nightly

### ISSUE THREAD

**Issue by nsaleille** [randy3k/SendTextPlus#12]
Hi, 

Thanks for this very awesome program. It works well for me with Sublime and iTerm Build 2.1.1for python code. However I get an error when I try to send some code to the latest iTerm2 nightly-build version. I get the following message in the sublime console:

subprocess.CalledProcessError: Command '['osascript', '-e', 'tell app "iTerm" to tell the first terminal window to tell current session to write text "import xxx"']' returned non-zero exit status 1

Any clue to fix that ?

Many thanks,
Nicolas

**Comment by randy3k** [comment]
The AppleScript syntax of iTerm keeps changing in the past few updates. I will take a look into it.

**Comment by nsaleille** [comment]
Great, that works ! Many thanks for your awesome work.
