### ISSUE TITLE
Detect Python blocks with '# %%' spyder cells

### ISSUE THREAD

**Issue by Naereen** [randy3k/SendTextPlus#13]
Spyder, Eclipse and ipython notebook all offer a Matlab-like way to define a cell in a Python file.
More details about this is explained [here on Spyder's doc](https://pythonhosted.org/spyder/editor.html#how-to-define-a-code-cell).

Could you try to add detect an entire block for a cell, starting with ``#%%`` or ``# %%`` ?

**Comment by randy3k** [comment]
Added 5ceadfcb31230813a13eabc79dc17e8da8d6b5e1
