### ISSUE TITLE
Sending code from different python scripts to different iTerm windows

### ISSUE THREAD

**Issue by jrzaurin** [randy3k/SendTextPlus#16]
I really like this package

However, when using sendText I am able to send code from, for example, two different sublime windows to two different iterm terminals where I have started ipython. 

Using sendText+ it always sends the code to one terminal no matter from which sublime script I am sending it. 

I am wondering:

1-If I can set up sendText+ to be able to send code to two different iterms from two different scripts (open in two different sublime windows)
2-How can I set a key-bind so command+enter is only used by sendText and some other command is used for sendText+ 

Anyway, great package.

thanks in advance for your time

Javier

**Comment by randy3k** [comment]
1. SendText+ always send the code the frontmost iTerm window. As long as you keep the target window in the front, SendText+ should be able to send to that window.
1. Yes, you can just overwrite the keybind in your user kepmap file.

**Comment by jrzaurin** [comment]
Hi Randy, 

thanks for your answer. 

1 - SendText+ , at least in my set up, sends the code to the foremost iTerm tab if they have been opened within the same window, i.e, with Cmd+T. However, if I open a new Window (Cmd+N) the code will always be sent to the one opened in the first place. I guess is because the first one will always be the foremost one (?).  This behaviour was not the behaviour with SendText, where I could select with the mouse the window to send code to.  Anyway, never mind, no big deal. 

2 - Yes, I know I can, the problem is that I cannot find the formula to do it, that's why I asked "how". To be more precise, for example, if I wanted alt+command+enter for SendText+ to send code, I should write something like this? (this of course, does not work):

`{ "keys": ["alt+cmd+enter"], "command": "sendText+_transfer_current"}`

Overall, I like the package I will use it anyway. 

Thanks again for your time.

**Comment by randy3k** [comment]
1 - I don't experience it with iTerm 2.9. It always send to the frontmost windows. cdd1c83 should improve the behavior.

2. We can check `Default (OSX).sublime-keymap`, `send_text_plus` is the command that you are looking for.
```
    {
        "keys": ["super+enter"],
        "command": "send_text_plus"
    }
```
