### ISSUE TITLE
 ctrl+shift+v ?

### ISSUE THREAD

**Issue by yueatwork** [randy3k/SendTextPlus#17]
Thank you for the update, great app.

I am wondering how to do the following?  

    Change the default paste all lines command from shift+insert to ctrl+shift+v. 

not familar with Cmder and I cannot find the following in Keys&Macro or Keys&Macro -> Paste

**Comment by randy3k** [comment]
![screen shot 2016-02-23 at 8 53 11 am](https://cloud.githubusercontent.com/assets/1690993/13253626/e868a3ee-da0a-11e5-8cd3-a61a110ab21b.png)

Hope it helps.

**Comment by yueatwork** [comment]
I think I have the same setting, but sublime doesn't send anything to Cmder.  I have:

1. Cmder in PATH
2. In Setting -> Keys&Macro -> Paste, unchecked [Comfirm <Enter> Keypress] and [Comfirm pasting more than ...]
3. In settings -> Keys&Macro, changed Paste clipboard contents to Ctrl+Shift_V
4. In sublime SendText+ -> User Setting added:

    {
        "defaults": [ {"platform": "window",  "prog": "Cmder" } ],
        "prog": null
    }

5. In sublime, Ctrl+Shift+P -> SendText+:Choose Program, selected [Defaults]
6. Restarted both Cmder and Sublime

But still, when I hit Ctrl+Enter, nothing got sent to the terminal.  I would like to configure it for python but now even my R-Box doesn't work.

Anything I did wrong?
