### ISSUE TITLE
sending text to ipython

### ISSUE THREAD

**Issue by yueatwork** [randy3k/SendTextPlus#20]
If we assume everyone is using ipython, would it be simpler if SendTextPlus just send the magic function %paste to the console, I believe this is a better approach than pasting everything into the console, as %paste does error checking.

**Comment by randy3k** [comment]
%cpaste doesn't work if you have ssh'ed into a server. It only works on local computers. See this [SO](http://stackoverflow.com/questions/8107261/ipython-paste-over-ssh-connection).
