### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jamuir1383** [randy3k/SendTextPlus#22]
Hi,

I'm having trouble sending to my R console now. This is a very recent problem as I used to be able to, but for the past 24-48 hours I've had issues sending. I can still send to my Terminal using SendText, but nothing seems to be working with SendText+ (R, RStudio, Terminal all don't work). I'm not sure what has happened. I have tried to uninstall/install multiple times and tried specifying the code with more detail, but still unable to get Sublime Text to send to R. Any suggestions would be much appreciated.

Thanks!

**Comment by randy3k** [comment]
Did you try to run `SendText+: Choose Program` in command palette?

**Comment by jamuir1383** [comment]
Yes, I have tried that for R, Rstudio, and Terminal and nothing works. I've also attempted different additional amounts of code to see if indicating a path name would help and it hasn't.

**Comment by jamuir1383** [comment]
I'm trying to run this on R version 3.2.3 for a MAC.

**Comment by randy3k** [comment]
Do you install both SendText and SendText+? You should only install SendText+. Is there any error in the console. What happens when you press cmd+enter? If the cursor advance to the next time, it means the package is working, but somehow the code is sent to a black hole.

**Comment by jamuir1383** [comment]
I have only SendText+ installed and have set to R in the command palette.

When I hit command+enter, nothing happens
When I hit command+b, it sources the current file as indicated

**Comment by randy3k** [comment]
It may mean some other packages have stolen the keybind.

**Comment by jamuir1383** [comment]
That pointed me in the right direction, thanks!!!!!!

**Comment by randy3k** [comment]
Do you mind telling me what was causing the issue?

**Comment by greensam** [comment]
Had same issue as original poster -- found out that I had both SendText and SendText+ installed.

**Comment by dpmccabe** [comment]
I also had this problem. R-Box had been working fine for years until the latest update that installed SendText+. `cmd+enter` was running the `r_box_send_selection`. I'm not sure where that was coming from, but I fixed it by adding this rule to my User keybindings file:

```
    {
        "keys": ["super+enter"], "command": "send_text_plus",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source, markup.raw.block.fenced.markdown" },
            { "key": "send_text_plus_keybinds", "operator": "equal", "operand": true }
        ]
    },
```

**Comment by randy3k** [comment]
@dpmccabe 
Sorry for the mess here, R-Box is undergoing a huge upgrade and the send text feature has been exported to SendText+. 

What you have defined in your user keybinding file is the default keybind defined by SendText+, you should be fine even without defining this in your own keybinding file. I suggest you to use this rather

```
   {
        "keys": ["super+enter"], "command": "send_text_plus",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source, markup.raw.block.fenced.markdown" }
        ]
    },
```

The `send_text_plus_keybinds` key is mainly for internal usage.

**Comment by dpmccabe** [comment]
Thanks, that also works. I probably have a duplicate `r_box_send_selection` I added in some other package's default keybinding but haven't tracked it down.
