### ISSUE TITLE
issue with custom commands

### ISSUE THREAD

**Issue by anasrana** [randy3k/SendTextPlus#23]
Hi, 

awesome package, just one small issue. When send text was built into R-box I had written a relatively
convoluted keybinding that allowed me to send a ?function to R to access the help function directly. I was utilising `r_box_send_selection` unfortunately with the new package I am struggling to find a way to implement that. Am I overlooking something or is that functionality gone?

Thank 
Anas

**Comment by randy3k** [comment]
In the version 6.0.2 of SendText+, you could define the following, however, due to a [bug](https://github.com/wbond/package_control_channel/issues/5283) of package control, the update is not yet available on Package Control.

```
{
         "keys": ["super+shift+h"], "command": "send_text_plus",
         "args": {"cmd": "?$selection"},
         "context": [
             { "key": "selector", "operator": "equal", "operand": "source.r" }
         ]
     },
```

**Comment by anasrana** [comment]
Thanks I will check it out when it is released.
