### ISSUE TITLE
Running the entire file in cmder

### ISSUE THREAD

**Issue by pingshunhuangalex** [randy3k/SendTextPlus#26]
Hi Randy

Just wonder if it's possible for you to add the function of running the entire script in terminal (cmder).

I think this can be realised by sending '%run ' + file_path into clipboard memory and sends it to the terminal shell.

Hope you have some time to implement this, it can make this plugin so much more powerful. Thanks.

**Comment by randy3k** [comment]
Does the default key "ctrl+b" do the job?

**Comment by pingshunhuangalex** [comment]
It does, but sublime console won't be able to take in interactive command like input. That's the reason I find my way to your doorstep. Also, if your plugin works, I'm actually thinking about ditching sublime build and stick to cmder to keep the experience consistent. Thanks.

**Comment by randy3k** [comment]
There should be an option "Python: Source File" when you press "ctrl+b", choosing that would send "%run <the file>" to cmder.
<img width="611" alt="screen shot 2016-03-06 at 11 11 25 pm" src="https://cloud.githubusercontent.com/assets/1690993/13560734/e25b0218-e3f0-11e5-9300-fa1ae3874701.png">

**Comment by pingshunhuangalex** [comment]
Thanks, then I guess it conflicts with sublime's build then. Is there a way to reset SendText+'s ctrl+b to something else? I'm not sure how to write this plugin's key binding... Sorry

**Comment by randy3k** [comment]
You would switch between different build systems by the menu "Tools -> Build System".

**Comment by pingshunhuangalex** [comment]
Right, I didn't realise it's a build system itself. Sorry for the question, you must find them quite stupid. Thanks again.
