### ISSUE TITLE
New SyntaxError when sending multiple lines to Terminal

### ISSUE THREAD

**Issue by Auerilas** [randy3k/SendTextPlus#29]
SendText Plus works great! Thanks for all of the work to make it. I just started to get a new error though. If I highlight multiple lines and hit Cmd+Enter to send them to Terminal, the lines run, but for some reason SendText (or SublimeText) started appending '--' to the end of the lines. The result is a SyntaxError:

For example, I sent the following five lines (including comments) to terminal by highlighting them in SublimeText and hitting Cmd+Enter. The lines run fine, but I receive:

    >>> %cpaste -q
      File "<stdin>", line 1
        %cpaste -q
        ^
    SyntaxError: invalid syntax

    >>> ### FRUIT MASS CLEAN
    ... # drop subplot 8D which is absnormally low
    ... fruitMass2 = fruitMass[~fruitMass['Subplot'].isin(['8D'])]
    >>> #average by subplot
    ... fruitMass_Plot = fruitMass2.groupby(['Plot', 'Subplot', 'Temperature', 'Herbivory'], as_index = False)['FruitMass'].mean()
     >>> --
      File "<stdin>", line 1
        --
         ^
     SyntaxError: invalid syntax

This error doesn't appear if I run lines one by one, or cut and paste from Sublime into Terminal. It DOES, however, appear when I run a code block (specified by # %%). So there's something weird about highlighting or multiple lines?

**Comment by randy3k** [comment]
it is specified to [ipython](https://ipython.org/). Since there is no way to correctly "copy and paste" commands to python console without the `%cpaste` magic. Try copy and paste all of the below and you will know why

```python
def f():
    x = 1

    # the space above would cause error
    print(x)
```

**Comment by Auerilas** [comment]
I quite literally just figured this out on my own, as well. This requires that I run the iPython notebook then?

**Comment by randy3k** [comment]
Not the notebook, but the ipython console,

![screen shot 2016-03-23 at 12 30 12 pm](https://cloud.githubusercontent.com/assets/1690993/13992578/02531fce-f0f3-11e5-8c40-178bb4d5be7a.png)

**Comment by Auerilas** [comment]
Perfect. Thanks!

**Comment by isezen** [comment]
Isn't it possible to support **bpython**  console? Because `%cpaste` blows up. Perhaps we may have a chance to set paste way in user settings?

**Comment by randy3k** [comment]
It is definitely possible, what does bpython handle copy and paste?

**Comment by randy3k** [comment]
I will close this thread for now.

@isezen you could open a separate thread for feature request.
