### ISSUE TITLE
Text not sent when Rterm is opened in Cmder

### ISSUE THREAD

**Issue by richardli** [randy3k/SendTextPlus#36]
I recently have to work on a windows machine and I'm trying to send text to a R session opened within Cmder, there's no response. But it works when I send text to Cmder directly (without opening Rterm). 

I could add Rgui to the settings so that lines will be sent to Rgui, but it is not great since Rgui is hard to use.

So I'm wondering if it is possible to send text to console when another application is opened in the console? Thanks!

**Comment by randy3k** [comment]
Did you open `Rterm.exe` or `R.exe`? I remember that it works with `R.exe`.

**Comment by richardli** [comment]
Thanks, I was using Rterm - It turns out I have to set the paste option to Ctrl + Shift + V instead of Ctrl + V. Then everything works.
