### ISSUE TITLE
AttributeError: 'int' object has no attribute 'decode' when sending to iTerm2

### ISSUE THREAD

**Issue by andrewrech** [randy3k/SendTextPlus#37]
I receive the following error when attempting to send a command to iTerm2. This was working several hours ago, I am not sure what changed in my system configuration.

> command: send_text_plus
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
>     return self.run(edit)
>   File "commands in /Users/andrewrech/Library/Application Support/Sublime Text 3/Installed Packages/SendTextPlus.sublime-package", line 81, in run
>   File "textsender in /Users/andrewrech/Library/Application Support/Sublime Text 3/Installed Packages/SendTextPlus.sublime-package", line 36, in send_text
>   File "textsender in /Users/andrewrech/Library/Application Support/Sublime Text 3/Installed Packages/SendTextPlus.sublime-package", line 105, in _dispatch_iterm
>   File "textsender in /Users/andrewrech/Library/Application Support/Sublime Text 3/Installed Packages/SendTextPlus.sublime-package", line 88, in iterm_version
> AttributeError: 'int' object has no attribute 'decode'

### ST3

Build 3101

### iTerm2

Build 2.9

**Comment by andrewrech** [comment]
Send to terminal normally. ITerm2 3.0.2 also does not work.

**Comment by randy3k** [comment]
Could you check that you have 0.6.11? there was a bug in 0.6.10 will break things.

**Comment by andrewrech** [comment]
I installed 0.6.11 and it is not working normally. Thank you!
