### ISSUE TITLE
Sending code to RStudio and Terminal?

### ISSUE THREAD

**Issue by danachandler** [randy3k/SendTextPlus#5]
Firstly, your programs are awesome! 

However, I'm not sure how to choose among them all (SendTextPlus, Enhanced-R, R-Box) in order to best accomplish the goal of being able to send code to both RStudio and Terminal. Any advice?

Ideally, I'd like to have:
ctrl+enter to send to RStudio
cmd+enter to send to Terminal

**Comment by randy3k** [comment]
I am sorry to tell you that support of RStudio has been deprecated in R-Box until RStudio supports applescript.

**Comment by randy3k** [comment]
With https://github.com/randy3k/SendTextPlus/pull/15, we could now send to RStudio web interference running on Chome/Safari (Mac).

**Comment by randy3k** [comment]
`SendTextPlus` and `R-Box` both support RStudio now.
