### ISSUE TITLE
Skipping blank lines.

### ISSUE THREAD

**Issue by okvs** [randy3k/SendTextPlus#9]
It would be great if this plugin was able to skip blank lines, and perhaps even commented lines. 

Comments are slightly more tricky, though, as one should distinguish between ordinary comments and block comments.

**Comment by randy3k** [comment]
it would be also tricky to skip blank lines.
For example, consider the following julia code

```julia
a = """
apple

orange
"""
```
The middle empty line is not really an empty line but a line in a string.

**Comment by okvs** [comment]
I think there is a slight misunderstanding. By 'skip' I do not mean that
blank lines should be discarded or ignored, but that the algorithm should not
stop on a blank line (or a commented line), but keep advancing (and sending lines) until it comes to the 
next non-empty, non-commented line.

Right now I sometimes come across code that looks like this:

    function foo()
        blah()
    end


    # jfklsdjfkljdsf
    # fjdsjfkdlsjfkldjs
    # jkdlsjfklds
    # fjildsjkfldsj
    # fjdksljfkdls

    function bar()
        bleh()
    end
I then need to hit cmd+enter 9 times to move to the function bar.

**Comment by randy3k** [comment]
er....it should work if you highlight the whole `a` stuff.

**Comment by okvs** [comment]
Is the skipping thing working? Or is it too difficult? I could have a go at it, but I don't actually know Python...

**Comment by randy3k** [comment]
Now, it skips blank lines. It will require more work to skip comments, I would probably not go for it now.

**Comment by okvs** [comment]
Great! :)

**Comment by randy3k** [comment]
I changed the default back to the old behavior, i.e., only advance to next line. The settings `auto_advance_non_empty` will control this. a85cd0b
